apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: azure-vote
  namespace: ambassador
spec:
  hostname: azure-vote.pacific.ca
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
      additionalPort: -1